In [61]:
# import libraries 
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
# this for inline visualization the 
# map or graph that we going to vizualize 
%matplotlib inline 

# Load the Data : Boston Housing Price Dataset

In [62]:
from sklearn.datasets import load_boston
boston = load_boston()

In [63]:
# check type of data 
type(boston)

sklearn.utils.Bunch

In [64]:
boston.keys()

dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename'])

In [65]:
# check the description of the entier dataset 
print(boston['DESCR'])

.. _boston_dataset:

Boston house prices dataset
---------------------------

**Data Set Characteristics:**  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pu

In [66]:
print(boston['data'])

[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]


In [67]:
print(boston['target'])

[24.  21.6 34.7 33.4 36.2 28.7 22.9 27.1 16.5 18.9 15.  18.9 21.7 20.4
 18.2 19.9 23.1 17.5 20.2 18.2 13.6 19.6 15.2 14.5 15.6 13.9 16.6 14.8
 18.4 21.  12.7 14.5 13.2 13.1 13.5 18.9 20.  21.  24.7 30.8 34.9 26.6
 25.3 24.7 21.2 19.3 20.  16.6 14.4 19.4 19.7 20.5 25.  23.4 18.9 35.4
 24.7 31.6 23.3 19.6 18.7 16.  22.2 25.  33.  23.5 19.4 22.  17.4 20.9
 24.2 21.7 22.8 23.4 24.1 21.4 20.  20.8 21.2 20.3 28.  23.9 24.8 22.9
 23.9 26.6 22.5 22.2 23.6 28.7 22.6 22.  22.9 25.  20.6 28.4 21.4 38.7
 43.8 33.2 27.5 26.5 18.6 19.3 20.1 19.5 19.5 20.4 19.8 19.4 21.7 22.8
 18.8 18.7 18.5 18.3 21.2 19.2 20.4 19.3 22.  20.3 20.5 17.3 18.8 21.4
 15.7 16.2 18.  14.3 19.2 19.6 23.  18.4 15.6 18.1 17.4 17.1 13.3 17.8
 14.  14.4 13.4 15.6 11.8 13.8 15.6 14.6 17.8 15.4 21.5 19.6 15.3 19.4
 17.  15.6 13.1 41.3 24.3 23.3 27.  50.  50.  50.  22.7 25.  50.  23.8
 23.8 22.3 17.4 19.1 23.1 23.6 22.6 29.4 23.2 24.6 29.9 37.2 39.8 36.2
 37.9 32.5 26.4 29.6 50.  32.  29.8 34.9 37.  30.5 36.4 31.1 29.1 50.
 33.3 3

In [68]:
# the feature inforation of the dataset 
print(boston['feature_names'])

['CRIM' 'ZN' 'INDUS' 'CHAS' 'NOX' 'RM' 'AGE' 'DIS' 'RAD' 'TAX' 'PTRATIO'
 'B' 'LSTAT']


## Prepare the dataset 

In [69]:
# creat the dataset 
# the DataFrame() - is used to created the entier dataset using the dataset which we load as whole 
#             but only we need some of the information so we have to choose the feature for the dataset 
#             thats what we going to do in this script 
dataset = pd.DataFrame(boston.data, columns=boston.feature_names)

In [70]:
dataset.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33

In [71]:
# create the output feature that we going to predict 
dataset['price'] = boston.target

In [72]:
dataset.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  price  
0     15.3  396.90   4.98   24.0  
1     17.8  396.90   9.14   21.6  
2     17.8  392.83   4.03   34.7  
3     18.7  394.63   2.94   33.4  
4     18.7  396.90   5.33   36.2

## Data Analysis


In [73]:
# check the whole set of information that the dataset we created 
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    float64
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    float64
 9   TAX      506 non-null    float64
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
 13  price    506 non-null    float64
dtypes: float64(14)
memory usage: 55.5 KB


In [74]:
# summrizing the stats of the data 
# this will be applied for all the numerical features and the categorical feature this will not apply
dataset.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean     3.613524   11.363636   11.136779    0.069170    0.554695    6.284634   
std      8.601545   23.322453    6.860353    0.253994    0.115878    0.702617   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082045    0.000000    5.190000    0.000000    0.449000    5.885500   
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.208500   
75%      3.677083   12.500000   18.100000    0.000000    0.624000    6.623500   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    68.574901    3.795043    9.549407  408.237154   18.455534  356.674032   
std     28.148861    2.105710    8.707259  168.537116    2.164946   91.294864   
min      2.900000    1.129600    1.000000  187.000000   12.600000    0.320000   
25%     45.025000    2.100175    4.000000  279.000000   17.400000  375.377500   
50%     77.500000    3.207450    5.000000  330.000000   19.050000  391.440000   
75%     94.075000    5.188425   24.000000  666.000000   20.200000  396.225000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT       price  
count  506.000000  506.000000  
mean    12.653063   22.532806  
std      7.141062    9.197104  
min      1.730000    5.000000  
25%      6.950000   17.025000  
50%     11.360000   21.200000  
75%     16.955000   25.000000  
max     37.970000   50.000000

### Checking the Null Values

In [75]:
dataset.isnull().sum()

CRIM       0
ZN         0
INDUS      0
CHAS       0
NOX        0
RM         0
AGE        0
DIS        0
RAD        0
TAX        0
PTRATIO    0
B          0
LSTAT      0
price      0
dtype: int64

As result showing there is no null value in the dataset 

## Exploratory Data Analysis (EDA)

 #### About default -  corr() method details
 by default the method used here for the correlation is pearson<br>
 the peasron correlation is basically check the relationship between two features like x and y <br>
 the output pearson correlation is between -1 to 1<br>
 more towards the 1 is highly positivley correlated <br>
 more towards the -1 is highly negativly correlted 

In [76]:
# chcek the correaltion between the features
dataset.corr()

CRIM        ZN     INDUS      CHAS       NOX        RM       AGE  \
CRIM     1.000000 -0.200469  0.406583 -0.055892  0.420972 -0.219247  0.352734   
ZN      -0.200469  1.000000 -0.533828 -0.042697 -0.516604  0.311991 -0.569537   
INDUS    0.406583 -0.533828  1.000000  0.062938  0.763651 -0.391676  0.644779   
CHAS    -0.055892 -0.042697  0.062938  1.000000  0.091203  0.091251  0.086518   
NOX      0.420972 -0.516604  0.763651  0.091203  1.000000 -0.302188  0.731470   
RM      -0.219247  0.311991 -0.391676  0.091251 -0.302188  1.000000 -0.240265   
AGE      0.352734 -0.569537  0.644779  0.086518  0.731470 -0.240265  1.000000   
DIS     -0.379670  0.664408 -0.708027 -0.099176 -0.769230  0.205246 -0.747881   
RAD      0.625505 -0.311948  0.595129 -0.007368  0.611441 -0.209847  0.456022   
TAX      0.582764 -0.314563  0.720760 -0.035587  0.668023 -0.292048  0.506456   
PTRATIO  0.289946 -0.391679  0.383248 -0.121515  0.188933 -0.355501  0.261515   
B       -0.385064  0.175520 -0.356977  0.048788 -0.380051  0.128069 -0.273534   
LSTAT    0.455621 -0.412995  0.603800 -0.053929  0.590879 -0.613808  0.602339   
price   -0.388305  0.360445 -0.483725  0.175260 -0.427321  0.695360 -0.376955   

              DIS       RAD       TAX   PTRATIO         B     LSTAT     price  
CRIM    -0.379670  0.625505  0.582764  0.289946 -0.385064  0.455621 -0.388305  
ZN       0.664408 -0.311948 -0.314563 -0.391679  0.175520 -0.412995  0.360445  
INDUS   -0.708027  0.595129  0.720760  0.383248 -0.356977  0.603800 -0.483725  
CHAS    -0.099176 -0.007368 -0.035587 -0.121515  0.048788 -0.053929  0.175260  
NOX     -0.769230  0.611441  0.668023  0.188933 -0.380051  0.590879 -0.427321  
RM       0.205246 -0.209847 -0.292048 -0.355501  0.128069 -0.613808  0.695360  
AGE     -0.747881  0.456022  0.506456  0.261515 -0.273534  0.602339 -0.376955  
DIS      1.000000 -0.494588 -0.534432 -0.232471  0.291512 -0.496996  0.249929  
RAD     -0.494588  1.000000  0.910228  0.464741 -0.444413  0.488676 -0.381626  
TAX     -0.534432  0.910228  1.000000  0.460853 -0.441808  0.543993 -0.468536  
PTRATIO -0.232471  0.464741  0.460853  1.000000 -0.177383  0.374044 -0.507787  
B        0.291512 -0.444413 -0.441808 -0.177383  1.000000 -0.366087  0.333461  
LSTAT   -0.496996  0.488676  0.543993  0.374044 -0.366087  1.000000 -0.737663  
price    0.249929 -0.381626 -0.468536 -0.507787  0.333461 -0.737663  1.000000

There are 2 types of correlation we need to check <br>
    1. correlation between independent feature<br>
    2. correlation between independent and dependent feature <br>
    
(1) if there is high correlation between independent feature, in this time we can remove one of the independent feature<br>
because that is what is called as multi-collinearity (if my 2 inpendent varible are verry highly correlated <br>
(like correled like 95% or 96% percent, or else negtive correlation also possible), here we can drop one the feature<br>
and just take the other one <br><br>

(2) the other one is the correlation between the independent and dependent features <br>

in comming step wil visulize the correlation and see how those are look 

In [ ]:
# let check with simple pairplot with seaborn
import seaborn as sns 
sns.pairplot(dataset)

# these graph we see hardly but if we have less number of feature thism

## Analyzing The Correlated Features

In [ ]:
# let check the relationship between the CRIMa and Price
plt.scatter(dataset['CRIM'], dataset['price'])
plt.xlabel('Crime Rate')
plt.ylabel('price of the house')

As the above chart we can see the inverse relationship between the feature Cime rate and price <br>
when the crime rate getting huge the price decrease

In [ ]:
# let check another postive correaltion avaergae number of room and price
plt.scatter(dataset['RM'], dataset['price'])
plt.xlabel('Average Number of Rooms')
plt.ylabel('price of the house')

In [ ]:
import seaborn as sns 
sns.regplot(x='RM',y='price',data=dataset)

The above chart is simllar to the scatter plot as we previously see but here we have simple linear line<br>
show the rlationship in better 

In [ ]:
# let see a negatively correlated feature
sns.regplot(x='LSTAT',y='price',data=dataset)

In [ ]:
# let see some of the feature not at all correlated 
sns.regplot(x='CHAS',y='price',data=dataset)

As we see above chart the both feature does not good correlation between them, that mean there is no linearity between 
 the feature 
 
 Linearity bassically mean when one feature increase or decrease the feature also should increas or decrease, if not there<br>
 is no linearity between the feature (the example is the above two features, those are doesn't have linear relationship <br> between them 

In [ ]:
sns.regplot(x='PTRATIO',y='price',data=dataset)

In [ ]:
# Create or Sepeartate Independent and Dependet variable/feature for further to develop the model 
x = dataset.iloc[:,:-1]
y = dataset.iloc[:,-1]

In [ ]:
# lets chek the x and y 
x.head()

In [ ]:
y.head()


In [ ]:
#  Here we going to do the train and test spit - which basically the proportion of split the dataset into test and train
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3, random_state=42)

In [ ]:
x_train

In [ ]:
y_train

In [ ]:
x_test

In [ ]:
y_test

### Standard Scalling 

The process is to stanadradize the all the value into same kind of value<br>
As we seeing the above datasets are having different different data value unit <br>
but when we comming to gradient descent (converging algorithm)  we need to normalize or standardize those all the data <br>points to same sacle, then it will fast the calculation <br>

this will be done based on standradize scalar 

### main aim in our linear regression to come near to the global minima 

In [ ]:
# Standardize the dataset
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [ ]:
x_train = scaler.fit_transform(x_train)

In [ ]:
# when ever try to apply to the test we dont use "fit_transform" but we only use "transform"
# because we have to make sure that whatever information i have with respect to the trainting dataset and whatever 
# techiniques i have applied for the transforming it the same techniques need to be applied to the test data
# this is done because to make sure that my model does not know much information about the test dataset
x_test = scaler.transform(x_test)

Here we going to pickle the model file (regression model file) so that we can further we can use this for deployment<br>
So these projects will be deply using dockers and take the github action

In [ ]:
# impoprt pickle library, this very important library to do th pickling
import pickle
pickle.dump(scaler,open("scalling.pkl","wb"))

###  But any way i have to look at why we using fit_transform for scaler.x_train and only <br><br>scaler.transform for x_test 

In [ ]:
x_train

In [ ]:
x_test 

### Why we standardize data

internally we using graident descent, our main aim to come global minima
to come to the global minima we have make sure that all <br>our independent feature
units should be in the same scale because of that the convergence will happen Quickly 

# Model Training 

In [ ]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()

In [ ]:
reg.fit(x_train, y_train)

In [ ]:
# lets check the coefficient and intercepts
print(reg.coef_)

For every feature there will be coefficient, here the changes of one unit that particular data point
how that going to effect the dependent variable/ target variable linearly (positively or negtively)

example

if CRIM point increase by one point the price will reduce as -1.108

In [ ]:
print(reg.intercept_)

In [ ]:
# on whcih parametters the model has been trained
reg.get_params()

In [ ]:
# do the prediction with the test data 
reg_pred = reg.predict(x_test)
reg_pred

## check whether model is good or bad iwith various charts 


## Assumptions

In [ ]:
## plot scatter plot for the prediction
plt.scatter(y_test, reg_pred)

when the scatter plot shows the prediction and actual values of plotting linear then that is good prediction model

In [ ]:
## prediction with residuals 
residuals = y_test - reg_pred
residuals

In [ ]:
## plotting this residuals 
sns.displot(residuals,kind='kde')

As we seeing this plot is look normal distribution but anyways there are some outliers can see on the right side


Beyond this the residulas should be normally get as normal distribution, but actually we achieved it

The range of the residual is 1 to -1

In [ ]:
### scatter plot respect to orediction and residuals 
## Uniformly distributed 
plt.scatter(reg_pred, residuals)


As you can see this scatter plot you seen that data points are uniformly scatter, there is not follwiing any kind kind <br>
distribution or format and this means that the model is performing well  

## Check the model with perfomance matrics 

In [ ]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error

In [ ]:
print(mean_squared_error(y_test,reg_pred))
print(mean_absolute_error(y_test,reg_pred))
print(np.sqrt(mean_squared_error(y_test,reg_pred)))

The above result basically indicate how the model actualy performing 

## R square and Adjuested R Square 

These are also very important perfomance metrics, when ever we create linear regression model

Formula 
### R^2 = 1 - SSR/SST

R^2 = Coefficient of Determination<br> SSR = sum of square of residuals <br> SST =  sum of square total

In [ ]:
from sklearn.metrics import r2_score
score= r2_score(y_test,reg_pred)
print(score)

The more towards the score actually good for the model

### Adjusted R2 = 1 - [(1-R2)*(n-1)/(n-k-1)]

Where:
<br><br>
R2: The R2 of the model <br>
n: The number of observations <br>
k: The number of predictor variables 

In [ ]:
ar2 = 1 - (1 - score) * (len(y_test)-1) / (len(y_test) - x_test.shape[1]-1)
print(ar2)

# NOTE 

### Have to Look at all individual performance metrics and understand the math and the concept behind them
### Also have to look at the differnt types of plots and make sure to understand the purpose of those plots and understand where to use those 

## New Data Prediction

Here we going to give the single data point from our dataset and check how the prediction can be done usin those data<br>
When we giving data to the model prediction we have to give that as 2 dimensional,so let see how these can be achieved<br>

In [ ]:
boston.data

In [ ]:
# let see how we can give the first data point and do the prediction 
# now changed the dimension to 2 dimension 
boston.data[0].reshape(1,-1).shape

In [ ]:
# lets transform the data points to same scale 
scaler.transform(boston.data[0].reshape(1,-1))

In [ ]:
# but anywasy when ever we going to give the data point o the prediction the standard step should be followed
# here we going do the scalling (we shiould make sure the data points are in the same types of value)
reg.predict(scaler.transform(boston.data[0].reshape(1,-1)))

## Picking the model File For Deployment

In [ ]:

pickle.dump(reg,open("regmodel.pkl","wb"))

as first parameter to this we passing the model object 
then what name and where it shoul be created <br>
the mode is "wb (write byte)": it will down all the content of the object inside this file <br><br>
The pickle is serialized format file, so that it can deploy in and server and problem if you want<br>
fo the prediction from the web application we can easily do it <br><br>

All the information of the model is stored as serilialized format, so that we can load it again and use as the model for prediction

In [ ]:
pickle.dump(reg,open("regmodel.pkl","wb"))

In [ ]:
# the pickle also can be loaded : now we have to read in "read byte" mode
pickled_model = pickle.load(open('regmodel.pkl','rb'))

In [ ]:
# lets predic with the pickled model 
pickled_model.predict(scaler.transform(boston.data[0].reshape(1,-1)))

Here we can see the result is same as we got from the model prediction for single data point

### Now we will focus on how to convert the entier project into and end-to-end project itself 

# NOTE
### 1. Learn About what is CI CD pipline in deployment of the model 
### 2. Follow the industrial formate to do the deploment, now we following but learn more 
###     (Use git, create ci cd pipe line,use cloud to load and deploy model)

#### if ypu didnt create file LICENSE,.gitignore, README no worries we can create those and <br><br>select the template from there in github